version: "3.4"
x-server: &server
  build: .
  volumes:
    - .:/usr/app/
    - /usr/app/node_modules/
  env_file:
    - '.env'
services:
  server:
    <<: *server
    command: npm run start
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "9229:9229" # for debug
