FROM node:dubnium-jessie
WORKDIR /usr/app
ARG ENVIRONMENT='production'
ARG API_LOG=false
ARG LOG_LEVEL='off'
ARG APP_PORT=3000
ARG MONGO_URI=
ARG REDIS_HOST=''
ARG REDIS_PORT=
ARG REDIS_PASSWORD=
ARG REDIS_DB=
ARG PRIVATE_API_TOKEN=''
ENV NODE_ENV=$ENVIRONMENT
ENV ENVIRONMENT=$ENVIRONMENT
ENV APP_PORT=$APP_PORT
RUN echo " BUILDING WITH ENVIRONMENT SET TO $ENVIRONMENT and NODE_ENV set to $NODE_ENV"
RUN echo "ENVIRONMENT=$ENVIRONMENT" >>  ".env.$ENVIRONMENT"
RUN echo "API_LOG=$API_LOG" >>  ".env.$ENVIRONMENT"
RUN echo "LOG_LEVEL=$LOG_LEVEL" >>  ".env.$ENVIRONMENT"
RUN echo "MONGO_URI=$MONGO_URI" >>  ".env.$ENVIRONMENT"
RUN echo "REDIS_HOST=$REDIS_HOST" >>  ".env.$ENVIRONMENT"
RUN echo "REDIS_PORT=$REDIS_PORT" >>  ".env.$ENVIRONMENT"
RUN echo "REDIS_PASSWORD=$REDIS_PASSWORD" >>  ".env.$ENVIRONMENT"
RUN echo "REDIS_DB=$REDIS_DB" >>  ".env.$ENVIRONMENT"
RUN echo "PRIVATE_API_TOKEN=$PRIVATE_API_TOKEN" >>  ".env.$ENVIRONMENT"
COPY . .
RUN  npm --production=false ci
RUN  npm run build
EXPOSE $APP_PORT
CMD [ "npm", "run", "start" ]
