export const PageRedirectionMap = {
  '/index.html': '/',
  '/bots.html': '/',
  '/bots/discord.html': '/',
  '/bots/line.html': '/',
  '/tourney.html': '/',
  '/watch.html': '/',
  '/game-developers.html': '/',
  '/brands-and-advertisers.html': '/',
  '/meet-tourney.html': '/',
  '/bots': `/`,
  '/bots/discord': '/',
  '/bots/line': '/',
  '/tourney': '/',
  '/watch': '/',
  '/game-developers': '/',
  '/brands-and-advertisers': '/',
  '/meet-tourney': '/',
  '/sitemap.xml': '/sitemap_index.xml',
};
