name: Build and Deploy to GKE

on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  KUBECONFIG: /root/config
  BUILD_NUMBER: qa-gametv-${{ git log -1 | head -1 | awk '{print $2}' }}
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: us-central1-a	
  GKE_CLUSTER: qa-gametv
  IMAGE: node:dubnium-jessie
  REGISTRY_HOSTNAME: gcr.io
  DEPLOYMENT_NAME: qa-gametv-app
  CLOUDSDK_PYTHON_SITEPACKAGES: 1


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    #- name: install python-openssl
    # run: sudo apt-get install -y python-openssl -o=Dpkg::Use-Pty=0

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}
        
    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
        gcloud components install kubectl
        
      
    # Build the Docker image
    - name: Check KUBE Folder
      run: | 
          sudo mkdir -p $HOME/.kube
          sudo chown $(id -u):$(id -g) $HOME/.kube/
          which gcloud
          
    - name: Export KUBECONFIG
      run: |
        sudo cp ./config $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config 
    - name: Kube Export
      run: export KUBECONFIG=$HOME/.kube/config
    - name: Check Config Content 
      run: sudo cat $HOME/.kube/config
    - name: Assign Permission to KUBECONFIG
      run: sudo chmod 777 -R $HOME/.kube/config
    - name: Check Config
      run: sudo kubectl config view
    - name: Build
      run: |        
        docker build --build-arg GITHUB_SHA="$GITHUB_SHA" --build-arg GITHUB_REF="$GITHUB_REF" --build-arg ENVIRONMENT=qa --build-arg MONGO_URI=mongodb+srv://gametvqa:pxnT6fZ3VSiIvWRw@qa-gametv-kjpap.gcp.mongodb.net/game-tv-v1 --build-arg PRIVATE_API_TOKEN=zUINSip5RwM6QWgOrcaoqWsra3nQITK --build-arg REDIS_HOST=35.223.116.199 --build-arg REDIS_PORT=6379 --build-arg REDIS_DB=0 -t gcr.io/game-tv-website-qa/$BUILD_NUMBER --no-cache .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push gcr.io/game-tv-website-qa/$BUILD_NUMBER
    
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        sudo kubectl set image deployment/qa-gametv-app qa-gametv-app=gcr.io/game-tv-website-qa/$BUILD_NUMBER --insecure-skip-tls-verify=true
      
    
