# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Set up secrets in your workspace: GKE_PROJECT with the name of the project, GKE_EMAIL with the service account email, GKE_KEY with the Base64 encoded JSON service account key (https://github.com/GoogleCloudPlatform/github-actions/tree/docs/service-account-key/setup-gcloud#inputs).
#
# 3. Change the values for the GKE_ZONE, GKE_CLUSTER, IMAGE, REGISTRY_HOSTNAME and DEPLOYMENT_NAME environment variables (below).

name: Build and Deploy to GKE

on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  KUBECONFIG: /root/config
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: us-central1-a	
  GKE_CLUSTER: qa-gametv
  IMAGE: node:dubnium-jessie
  REGISTRY_HOSTNAME: gcr.io
  DEPLOYMENT_NAME: qa-frontend-test
  CLOUDSDK_PYTHON_SITEPACKAGES: 1


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    #- name: install python-openssl
    # run: sudo apt-get install -y python-openssl -o=Dpkg::Use-Pty=0

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
        gcloud components install kubectl
        
      
    # Build the Docker image
    - name: Check KUBE Folder
      run: | 
          sudo mkdir -p $HOME/.kube
          sudo chown $(id -u):$(id -g) $HOME/.kube/
          
    - name: Export KUBECONFIG
      run: |
        sudo cp ./config $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config 
    - name: Kube Export
      run: export KUBECONFIG=$HOME/.kube/config
    - name: Check Config Content 
      run: sudo cat $HOME/.kube/config
    - name: Assign Permission to KUBECONFIG
      run: sudo chmod 777 -R $HOME/.kube/config
    - name: Check Config
      run: sudo kubectl config view
    
