name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '278.0.0'
        service_account_email: anil.kumar@bluestacks.com
        service_account_key: ${{ secrets.GAMETV }}
    - run: gcloud info
